#!/bin/bash
file /tmp/my_first_directory
echo file /tmp/my_first_directory
file /tmp/my_first_directory
file /tmp/my_first_directory: directory
file /tmp/my_first_directory/
mkdir /tmp/My_first_directory/
